### ISSUE TITLE
Armor paint cannot be compiled

### ISSUE THREAD

**Issue by Devadityakumar** [armory3d/armortools#1749]
**ArmorPaint version:**

latest

**OS / GPU model:**
Windows 11 pro

**Issue description:**
Using ArmorCore from C:\Users\WDAGUtilityAccount\armortools\armorcore
Creating windows project files.
ReferenceError: Platform is not defined
    at  (<input>:5:18)
    at <eval> (<input>:18:3)
    at load_project (make.js:2340:92)
    at addProject (make.js:3247:36)
    at  (<input>:59:35)
    at <eval> (<input>:130:3)
    at loadproject (make.js:2340:92)
    at addProject (make.js:3247:36)
    at  (<input>:9:1)
    at <eval> (<input>:48:3)

I got this error everytime i used the make command in cmd for compiling

**Steps to reproduce:**

**Comment by Devadityakumar** [comment]
Bro I did the most illogical thing ever but that worked.I just found a file named krom.cid or krom.cd and renamed it as krom.js and Armorpaint started working
